# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        ApplicationBundle\Entity\GhAdmin: bcrypt
        ApplicationBundle\Entity\GhUser: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        ghadmin_provider:
            entity:
                class: ApplicationBundle:GhAdmin
                # if you're using multiple entity managers
                # manager_name: customer
        ghuser_provider:
            entity:
                class: ApplicationBundle:GhUser
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                login_path: /propLogin
                #check_path: /propLogin

            provider: ghadmin_provider

            logout:
               path: /logout
               target: /

        ghadmin_firewall:
            anonymous: ~
                # activate different ways to authenticate

                # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                login_path: /propLogin
                #check_path: /propLogin

            provider: ghadmin_provider

            logout:
                path: /logout
                target: /

        ghuser_firewall:
            anonymous: ~
                        # activate different ways to authenticate

                        # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            form_login:
                login_path: /

            provider: ghuser_provider

            logout:
                path: /logout
                target: /

    access_control:
            # require ROLE_ADMIN for /admin*
            #- { path: ^/propDashboard, roles: ROLE_GHADMIN }
            #- { path: ^/propMaison, roles: ROLE_GHADMIN }
            #- { path: ^/propCommentaires, roles: ROLE_GHADMIN }
            #- { path: ^/propRegister, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            #- { path: ^/propLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
