<?php

namespace ApplicationBundle\Repository;

/**
 * GhAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
