<?php

namespace ApplicationBundle\Repository;

/**
 * GhouseImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhouseImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
