<?php

namespace ApplicationBundle\Repository;

/**
 * GhouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhouseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllValidated()
    {
        return $this->findBy(array('is_validated' => 1));
    }

    public function findAllValidatedNewest()
    {
        return $this->findBy(array('is_validated' => 1), array('dateCreated' => 'DESC'));
    }
}
