<?php

namespace ApplicationBundle\Repository;

/**
 * GhouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhouseRepository extends \Doctrine\ORM\EntityRepository
{
}
