<?php

namespace ApplicationBundle\Repository;

/**
 * GhUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhUserRepository extends \Doctrine\ORM\EntityRepository
{
}
