<?php

namespace ApplicationBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * GhUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhUserRepository extends \Doctrine\ORM\EntityRepository //implements UserLoaderInterface
{
    public function loadUserByUsername($username, $password, $passwordEncoder)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult();

        if (null === $user) {
            return false;
        }
        if (!$passwordEncoder->isPasswordValid($user, $password)) {
            return false;
        }
        return $user;
        // $check_password  = $this->getContainer()->get('security.password_encoder')->isPasswordValid($user, $password);
    }

}
