<?php

namespace ApplicationBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * GhUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhUserRepository extends \Doctrine\ORM\EntityRepository //implements UserLoaderInterface
{
    /*public function verifyLogin($username,$password ){
       $check_user = $this->getEntityManager()
            ->getRepository(GhUser::class)
            ->findOneBy(array('username' => $username));
        $check_user =  $this->getEntityManager()
            ->createQuery(
                'SELECT * FROM ApplicationBundle:GhUser'
            )
            ->getResult();

        if ($check_user){
            #$check_password = $passwordEncoder->isPasswordValid($check_user, $login_form->get('password')->getData());
            $check_password  = $this->get('security.password_encoder')->isPasswordValid($check_user, $password);
            if ($check_password){
                return true;
            }
            return false;
            ){
                echo 'password equal';
            }
        }
        return false;

    }*/
    public function loadUserByUsername($username, $password, $passwordEncoder)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult();

        if (null === $user) {
            return false;
        }
        if (!$passwordEncoder->isPasswordValid($user, $password)) {
            return false;
        }
        return $user;
        // $check_password  = $this->getContainer()->get('security.password_encoder')->isPasswordValid($user, $password);
    }

}
